parameters:
    bluegrass.metadata_provider_factory_default_locator.class: Bluegrass\Metadata\Bundle\MetadataBundle\Model\MetadataProvider\Factory\Locator\MetadataProviderFactoryDefaultLocator
    bluegrass.metadata_provider_factory.class: Bluegrass\Metadata\Bundle\MetadataBundle\Model\MetadataProvider\Factory\MetadataProviderFactory

services:

  bluegrass.metadata_provider_factory_default_locator:
        class: %bluegrass.metadata_provider_factory_default_locator.class%
        arguments: []
  
  bluegrass.metadata_provider_factory:
        class: %bluegrass.metadata_provider_factory.class%
        arguments: [ @doctrine.orm.entity_manager ]
        calls:
            - ['setMetadataProviderFactoryLocator', ["@bluegrass.metadata_provider_factory_default_locator"]]

  